// <auto-generated />
using System;
using DataBase2Project;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataBase2Project.Migrations
{
    [DbContext(typeof(EFDBConn))]
    [Migration("20240206231342_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DataBase2Project.BeerDbModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("alcohol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("blg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ibu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("malts")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("style")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("uid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("yeast")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Beers");
                });
#pragma warning restore 612, 618
        }
    }
}
